language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  global:
  - WARN_AS_ERROR=1
  matrix:
  - CC_FLAGS= DEBUG=0
  - CC_FLAGS="-DPRIVILEGE_CHECKS -DBOUNDS_CHECKS" DEBUG=1
  - CC_FLAGS=-DLEGION_SPY DEBUG=1
  - CC_FLAGS=-std=c++0x DEBUG=0
matrix:
  exclude:
    - os: osx
      compiler: gcc
# blacklist some branches
branches:
  except:
    - deppart
    - rdir
before_install:
  - |
    if [ "$(uname)" = "Linux" ]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo apt-get update -qq
      sudo apt-get install -qq g++-4.9 clang-3.5
    fi
  - if [ "$(uname)" = "Linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$(uname)" = "Linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
  - export LG_RT_DIR="$PWD/runtime"
script:
  - ./language/travis.py
  - |
    make -s -C examples/00_hello_world clean
    make -s -C examples/00_hello_world -j2
    examples/00_hello_world/hello_world
    make -s -C examples/01_tasks_and_futures
    examples/01_tasks_and_futures/tasks_and_futures
    make -s -C examples/02_index_tasks
    examples/02_index_tasks/index_tasks
    make -s -C examples/03_global_vars
    examples/03_global_vars/global_vars
    make -s -C examples/04_logical_regions
    examples/04_logical_regions/logical_regions
    make -s -C examples/05_physical_regions
    examples/05_physical_regions/physical_regions
    make -s -C examples/06_privileges
    examples/06_privileges/privileges
    make -s -C examples/07_partitioning
    examples/07_partitioning/partitioning
    make -s -C examples/08_multiple_partitioning
    examples/08_multiple_partitioning/multiple_partitioning
    make -s -C examples/09_custom_mapper
    examples/09_custom_mapper/custom_mapper
    make -s -C examples/full_circuit
    examples/full_circuit/ckt_sim
    make -s -C examples/full_ghost
    examples/full_ghost/ghost -ll:cpu 4
  - |
    if [ $DEBUG -eq 0 ]; then
      make -s -C test/realm USE_CUDA=0 USE_GASNET=0 clean
      make -s -C test/realm USE_CUDA=0 USE_GASNET=0 run_all
    fi
  - |
    if [ $DEBUG -eq 0 ]; then
      make -s -C test/performance/realm clean_all
      make -s -C test/performance/realm run_all
    fi
